### ISSUE TITLE
Released package with these changes?

### ISSUE THREAD

**Issue by haf** [nrayburn-tech/node-http-proxy#4]
Hi,

Did you ever release these changes as a package?

I've looked through all network/forks for the original lib and yours is the most improved.

**Comment by nrayburn-tech** [comment]
I have not released the changes.  While I think that all the changes I have made so far work and are beneficial, none of the changes are documented and I haven't really tested it enough myself to be comfortable suggesting it for somebody else to use.

Feel free to use it if you want, and I can try to help with any issues you might run into.  However, I definitely wouldn't recommend using it unless you really need a change that has been made here and not in the original library.  Even then, I would likely suggest you making your own patch locally with something like `patch-package` instead of using this.

If the project does get to the point where I am comfortable with others using it, I would definitely update the changelog and release it to npm.

**Comment by nrayburn-tech** [comment]
@haf I have created https://github.com/nrayburn-tech/node-http-proxy/issues/5 which has a list of things needed, prior to me making a release.  The only real blocker from making a beta release is for me to figure out an organization name to publish an `http-proxy` package under.  Once that is done, there will be a release available to use.

I'm going to close this, you should be able to follow the other issue for any updates.  I'm hoping to have at least a beta out this week.
